name = "Newb X Aero"
version = [1, 0, 0]
min_supported_mc_version = [1, 26, 30]

description = '''
§bNewb X Aero
§7Enhanced vanilla RenderDragon shader.
§7Cinematic lighting, vibrant colors,
§7clear water, smooth atmosphere,
§7and optimized performance.
§aVersion %v
'''

authors = ["Goboyy22"]
url = "https://github.com/Goboyy22/Newb-X-Aero"

uuid = "8e2a4d69-7c3b-4a8f-9d73-5f1b8c42e917"

materials = [
"Sky",
"RenderChunk",
"Actor",
"ActorGlint",
"EndSky",
"Clouds",
"SunMoon",
"Weather",
"ItemInHandTextured",
"ItemInHandColor",
"ItemInHandColorGlint",
"Stars"
]

[info]

copyright = '''
Copyright © 2026 Goboyy22.

Newb X Aero is an enhanced RenderDragon shader based on the open-source Newb Shader project.

Original Newb Shader
Copyright © devendrn and Newb Shader Contributors.

Modifications, visual redesign, optimization, configuration, and additional features:
© 2026 Goboyy22.

Please provide proper credit when redistributing this shader.
Do not claim this project as entirely your own.
'''

credits = '''
Newb X Aero

Developer
• Goboyy22

Based On
• Newb Shader by devendrn

Special Thanks
• Newb Shader Contributors
• Minecraft Bedrock Community
• Everyone who tested and supported this project
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default
[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No Wave + No Fog
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No Fog
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No Wave
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
